version: '3.9'

services:

  mysql-kc:
    image: mysql:8.0.27
    ports:
      - 3366:3306
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    environment:
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8181:8080
    command: start-dev
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin_user
      KEYCLOAK_ADMIN_PASSWORD : admin_password
      KC_DB_PORT: 3306
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-kc
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password      
      
      
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume: